name: Docker Build, Run, Save Artifacts

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t box-watch .

      - name: Run the Docker container
        run: docker run box-watch
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Copy files from mounted volume to workspace
        run: docker cp box-watch:/app/aws_data .

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-images
          path: ./aws_data