name: Docker Build, Run, Save Artifacts

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t box-watch .

      - name: Make data dir
        run: mkdir $GITHUB_WORKSPACE/aws_data

      - name: Run the Docker container
        run: docker run -v $GITHUB_WORKSPACE/aws_data:/app/aws_data box-watch
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      
      - name: List files in aws_data directory
        run: ls $GITHUB_WORKSPACE/aws_data

      - name: Print wd
        run: pwd

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-images
          path: $pwd/aws_data