name: Docker Build and Download News
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t box-watch .

      - name: Make data dir
        run: mkdir $GITHUB_WORKSPACE/news_stories

      - name: Run the Docker container
        run: docker run -v $GITHUB_WORKSPACE/news_stories:/app/news_stories box-watch
      
      - name: List files in aws_data directory
        run: ls $GITHUB_WORKSPACE/news_stories

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-stories
          path: /home/runner/work/box-watch/box-watch/news_stories